[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$mVM0M5R.$KiqtZJpy8X8edwiL53pP3."
  ]
[http.routers.api]
  rule = "Host(`traefik.capass.codes`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"