version: '3.5'

volumes:
  uptime-kuma:
    driver: local
    
networks:
  proxy:
    external: true

services:
  app:
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - uptime-kuma:/app/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.port: 3001
      traefik.http.routers.uptime.entryPoints: https
      traefik.http.routers.uptime.rule: Host(`uptime.$DOMAIN`)


