version: '3.3'

networks:
  proxy:
    external: true
  backend:
    external: true

volumes:
  nc-data:
    external: true
  nc-config:

services:
  app:
    image: nextcloud:stable-fpm
    restart: always
    volumes:
      - nc-data:/data
      - nc-config:/var/www/html
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.capass.org
      - NEXTCLOUD_UPDATE=1
      - TRUSTED_PROXIES=172.19.0.0/24
      - NEXTCLOUD_DATA_DIR=/data
    networks:
      - backend
      - default

  web:
    image: nginx:alpine
    restart: always
    volumes_from:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.cloud.entryPoints: https
      traefik.http.routers.cloud.tls: true
      traefik.http.routers.cloud.rule: Host(`cloud.capass.org`)
      traefik.http.routers.cloud.middlewares: nextcloud-caldav@docker,nextcloud-wellknown@docker
      # middleware definition
      traefik.http.middlewares.nextcloud-caldav.replacepathregex.regex: ^/.well-known/(card|cal)dav
      traefik.http.middlewares.nextcloud-caldav.replacepathregex.replacement: /remote.php/dav/
      traefik.http.middlewares.nextcloud-wellknown.replacepathregex.regex: ^(/.well-known.*)
      traefik.http.middlewares.nextcloud-wellknown.replacepathregex.replacement: /index.php$${1}
      traefik.http.middlewares.nc-header.headers.stsSeconds: 15552000
      traefik.http.middlewares.nc-header.headers.forceSTSHeader: true
      traefik.http.middlewares.nc-header.headers.stsPreload: true
      traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nc-header.headers.browserXssFilter: true
      traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: SAMEORIGIN
      traefik.http.middlewares.nc-header.headers.contentSecurityPolicy: "default-src 'self';frame-ancestors 'self';style-src 'self' 'unsafe-inline';script-src 'self' 'unsafe-inline' 'unsafe-eval';img-src 'self' data:;font-src 'self' data:"

  cron:
    image: nextcloud:stable-fpm
    restart: always
    depends_on:
      - app
    volumes:
      - nc-data:/data
      - nc-config:/var/www/html
    entrypoint: /cron.sh
    networks:
      - backend
