version: '3.3'

networks:
  proxy:
    external: true
  backend:
    external: true

volumes:
  nc-data:
    external: true

services:
  app:
    image: nextcloud:25.0-fpm-alpine
    restart: always
    volumes:
      - nc-data:/var/www/html
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@nextcloud2022
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_PASSWORD=@nextcloud-Alarmfox97
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.capass.org
    networks:
      - backend
      - default

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - nc-data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.cloud.entryPoints: https
      traefik.http.routers.cloud.tls: true
      traefik.http.routers.cloud.rule: Host(`cloud.capass.org`)
      traefik.http.routers.cloud.middlewares: nextcloud-caldav@docker,nextcloud-wellknown@docker
      # middleware definition
      traefik.http.middlewares.nextcloud-caldav.replacepathregex.regex: ^/.well-known/(card|cal)dav
      traefik.http.middlewares.nextcloud-caldav.replacepathregex.replacement: /remote.php/dav/
      traefik.http.middlewares.nextcloud-wellknown.replacepathregex.regex: ^(/.well-known.*)
      traefik.http.middlewares.nextcloud-wellknown.replacepathregex.replacement: /index.php$${1}
      traefik.http.middlewares.nc-header.headers.stsSeconds: 15552000
      traefik.http.middlewares.nc-header.headers.forceSTSHeader: true
      traefik.http.middlewares.nc-header.headers.stsPreload: true
      traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nc-header.headers.browserXssFilter: true
      traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: SAMEORIGIN
      traefik.http.middlewares.nc-header.headers.contentSecurityPolicy: "default-src 'self';frame-ancestors 'self';style-src 'self' 'unsafe-inline';script-src 'self' 'unsafe-inline' 'unsafe-eval';img-src 'self' data:;font-src 'self' data:"

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - nc-data:/var/www/html
    entrypoint: /cron.sh
    networks:
      - backend

  hbp:
    image: icewind1991/notify_push:0.5.2
    restart: always
    networks:
      - proxy
      - backend 
    environment:
      - DATABASE_URL=postgres://postgres:@nextcloud2022@postgresql:5432/postgres?sslmode=disable
      - DATABASE_PREFIX=oc_
      - REDIS_URL=redis://redis
      - NEXTCLOUD_URL=http://web
    labels:
      traefik.enable: true
      traefik.http.routers.hbp.entryPoints: https
      traefik.http.routers.hbp.tls: true
      traefik.http.routers.hbp.rule: Host(`cloud.capass.org`) && PathPrefix(`/push`)
      traefik.http.services.hbp.loadbalancer.server.port: 7867
    depends_on:
      - web
    cap_add:
      - MKNOD
