networks:
  proxy:
    external: true

volumes:
  wellnessdata:
 
services:
  app:
    image: ghcr.io/alarmfox/wellness-nutrition:v1.1.0
    environment:
      - DATABASE_URL=
      - EMAIL_SERVER_HOST=
      - EMAIL_SERVER_PORT=
      - EMAIL_SERVER_USER=
      - EMAIL_SERVER_PASSWORD=
      - EMAIL_FROM=
      - EMAIL_NOTIFY_ADDRESS=
      - NEXTAUTH_SECRET=
      - NEXTAUTH_URL=
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_HOST=
      - PUSHER_APP_PORT=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_USE_TLS=
      - PUSHER_APP_CLUSTER=
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.app.entryPoints: https
      traefik.http.routers.app.tls: true
      traefik.http.routers.app.rule: Host(`wellnessdemo.capass.org`)
      traefik.http.services.app.loadbalancer.server.port: 3000
 
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    environment:
      - SOKETI_DEBUG=0
      - SOKETI_DEFAULT_APP_ID=
      - SOKETI_DEFAULT_APP_KEY=
      - SOKETI_DEFAULT_APP_SECRET=
      - SOKETI_DB_REDIS_HOST=redis
    networks:
     - proxy
     - default 
    labels:
      traefik.enable: true
      traefik.http.services.soketi.loadbalancer.server.port: 6001
      traefik.http.routers.soketi.entrypoints: http
      traefik.http.routers.soketi-secure.entrypoints: https
      traefik.http.routers.soketi-secure.rule: Host(`soketi.capass.org`)
      traefik.http.routers.soketi.rule: Host(`soketi.capass.org`)
      traefik.http.routers.soketi.middlewares: soketi-https-redirect
      traefik.http.middlewares.soketi-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.soketi-secure.tls.certresolver: cloudflare

  redis:
    image: redis:alpine
    networks:
        - default

  db:
    image: postgres:14.7
    environment:
      - POSTGRES_PASSWORD=
    networks:
      - default
    volumes:
      - wellnessdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
