version: '3.3'

networks:
  backend:
    external: true

volumes:
  pg-data:

services:
  postgresql:
    image: postgres:14.6-alpine3.17
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

