version: '3.3'

networks:
  proxy:
    external: true
  backend:
  frontend:

volumes:
  db:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/HC_Volume_16343352/nextcloud

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - app:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - backend
      - frontend

  web:
    build: ./web
    restart: always
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app
    networks:
      - proxy
      - frontend
    labels:
      - traefik.http.routers.cloud.rule=Host(`cloud.$DOMAIN`)
      - traefik.http.routers.cloud.middlewares=nextcloud-caldav@docker
      - traefik.http.routers.cloud.tls=true
      - traefik.http.routers.cloud.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
      - traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https
      - traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - backend

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt 
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt 
  postgres_db:
    file: ./postgres_db.txt
  postgres_password:
    file: ./postgres_password.txt 
  postgres_user:
    file: ./postgres_user.txt
