version: '3.3'

networks:
  proxy:
    external: true

volumes:
  db:
  doc_cache:
  doc_logs:

services:
  office:
    image: onlyoffice/documentserver
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PASSWORD}
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - AMQP_URI=amqp://guest:guest@broker
      - JWT_ENABLED=true
      - "JWT_SECRET=${JWT_SECRET}"
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    networks:
      - proxy
      - default
    volumes:
      - doc_logs:/var/log/onlyoffice
      - doc_cache:/var/lib/onlyoffice
    labels:
      traefik.enable: true
      traefik.http.routers.office.rule: Host(`office.$DOMAIN`)
      traefik.http.routers.office.entryPoints: https
      traefik.http.routers.office.middlewares: secure-headers

      # middleware definition
      traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto: https

  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

  broker:
    image: rabbitmq
    restart: always

